In [1]:
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'], 
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)

# Replace 'Thirty' with '30'
df['Feature1'] = df['Feature1'].replace('Thirty', '30')

# Now convert to int
df['Feature1'] = df['Feature1'].astype(int)

print(df)

   Feature1  Feature2
0        10       5.5
1        20       6.7
2        30       8.9


In [2]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value,inplace = True)  # Error: fillna() does not modify in place

print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [3]:
from sklearn.linear_model import LinearRegression
import numpy as np

X = np.array([1, 2, 3, 4, 5]).reshape(-1,1)  # Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [10]:
X

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50]).reshape(-1,1) # Error: Should be 2D

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [30]:
#5.
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)
model = LogisticRegression()
model.fit(X, y_encoded)


LogisticRegression()

In [32]:
print(y_encoded)

[1 0 1]


In [42]:
#6.import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[['Category']])  # Error: Data should be reshaped
print(encoded)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


In [58]:
#6.
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0,1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state = 0)


In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels
encoder= LabelEncoder()
y_encoded = encoder.fit_transform(y_train)
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [64]:
print(y_encoded)

[1 0 1]


In [68]:
#8.
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])
imputer = SimpleImputer(strategy = 'mean')
X_train_imputed = imputer.fit_transform(X_train)
model = LinearRegression()
model.fit(X_train_imputed, y_train)  

LinearRegression()

In [72]:
X_train_imputed

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [74]:
#9.
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["spam", "ham", "spam"]  # Error: String labels not allowed
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y_train)
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [76]:
print(y_encoded)

[1 0 1]


In [78]:
#10.
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference

[0]
